#  ____   __     __  ____     ____                   _                    _
# |  _ \  \ \   / / |  _ \   / ___|   ___    _ __   | |_   _ __    ___   | |
# | |_) |  \ \ / /  | |_) | | |      / _ \  | '_ \  | __| | '__|  / _ \  | |
# |  __/    \ V /   |  __/  | |___  | (_) | | | | | | |_  | |    | (_) | | |
# |_|        \_/    |_|      \____|  \___/  |_| |_|  \__| |_|     \___/  |_|
#                                                                             by IdkMan

General:
  # Here you can change language of the plugin, currenty supported languages: EN, PL
  # If you want to introduce your own language contact me on SpigotMC (https://www.spigotmc.org/members/idkman.257368/)
  language: EN
  # This number specifies the version of the configuration that will change with new updates.
  configVersion: 1

PVP:
  # How long PVP mode should be?
  timeInPVPMode: 15
  # Turn off `fly` on pvp. The PVP mode will also be turned on if you hit another player from the bow.
  turnOffFlyOnPVP: true
  # Disable invisibility potion. Doesn't disable vanish.
  disableInvisibilityOnPVP: false
  # Should we block chorus fruit teleport?
  blockChorusFruitsTeleport: true
  # Should we block ender pearl teleport?
  blockEnderPeralsTeleport: true
  # Should player be killed and items dropped on the ground when logging out during PVP?
  killWhenLogoutDuringPVP: true
  # Should we broadcast info to all players, that the player log out during PVP?
  # This option will be ignored if `KillWhenLogoutOnPVP` option is set to FALSE.
  broadcastPlayerKilledInfo: true

Commands:
  # Should all commands be blocked during PVP?
  blockAll: false
  # If `BlockAllCommands` is set to TRUE then you can define below commands that will be AVAILABLE during PVP.
  # If `BlockAllCommands` option is set to FALSE then this option is ignored.
  # You don't need to care about the case sensitiveness of commands.
  # Example: - msg
  whitelist:
    - msg
    - tell
    - whisper
  # If `BlockAllCommands` is set to TRUE then this option is ignored.
  # If `BlockAllCommands` option is set to FALSE you can define below commands that will be BLOCKED during PVP.
  # You don't need to care about the case sensitiveness of commands.
  # Example: - spawn
  blacklist:
    - spawn
    - tpa
    - tpayes
    - tpyes
    - tpaccept
    - tpadeny
    - tpdeny
    - tp
    - teleport
  # All commands that will be executed in console when player log out during PVP. You can use %player% variable.
  # Commands should be written without a preceding slash "/"
  # Example: - eco set %player% 0
  executedWhenLogoutDuringPVP: []

Integrations:
  # Options below works only when supported version of EssentialsX is installed on the server.
  EssentialsX:
    # Turn off God Mode on hit and enter PVP mode
    disableGodModeOnHit: false

# Not enough features? Let me know what you want! Write private message to me on spigot @IdkMan
# or describe your problem on discussion page of this plugin.