package com.gmail.nowyarek.pvpcontrol.io;

public enum Text {
    /* # CHAT & PREFIXES */
    PLUGIN_PREFIX, ERROR_PREFIX, WARNING_PREFIX, INFO_PREFIX, SUCCESS_PREFIX, LOG_PREFIX, DEBUG_PREFIX,

    /* # PLUGIN */
    MISSING_LANGUAGE_STATEMENTS, OLD_CONFIG, LANGUAGE_NOT_SUPPORTED, PLUGIN_ENABLED, PLUGIN_DISABLED, RELOAD_COMPLETE,

    /* # PVP */
    YOU_ARE_IN_PVP, YOU_ARE_NOT_IN_PVP, COMMANDS_NOT_ALLOWED_DURING_PVP, THIS_COMMAND_IS_NOT_ALLOWED_DURING_PVP,
    PLAYER_LOG_OUT_DURING_PVP_SERVER_BROADCAST, TELEPORTING_NOT_ALLOWED_DURING_PVP, CHORUS_FRUIT_NOT_ALLOWED_DURING_PVP,
    ENDER_PEARL_NOT_ALLOWED_DURING_PVP, PVP_MODE_ON, PVP_MODE_OFF,

    /* # HOOKS */
    PLUGIN_HOOKED_BUT_WAS_NOT_RECOGNIZED, GOD_MODE_HAS_BEEN_DISABLED,

    /* # COMMANDS */
    INCORRECT_COMMAND_SYNTAX, COMMAND_NOT_ENOUGH_ARGUMENTS, COMMAND_TOO_MUCH_ARGUMENTS, COMMAND_NOT_ALLOWED_FOR_CONSOLE, COMMAND_NO_PERMISSIONS,
    COMMAND_PVPCONTROL_USAGE, SUB_COMMAND_HELP_USAGE,
    SUB_COMMAND_RELOAD_USAGE, SUB_COMMAND_RELOAD_RELOADED_SUCCESSFULLY,
    COMMAND_PVP_YOU_ARE_STILL_ON_PVP, COMMAND_PVP_YOU_ARE_NOT_ON_PVP,

    /* # OTHER */
    THEMATIC_BREAK, HELP_TITLE, HELP_COMMAND_ENTRY, HELP_NEXT_PAGE_INFO, HELP_LAST_PAGE_INFO, HELP_INCORRECT_PAGE
}
