name: "PvPControl_API_Consumer"
main: "com.example.plugin_consumer.pvpcontrol.PvPControl_API_Consumer"
version: "@PLUGIN_VERSION@"
author: "@PLUGIN_AUTHOR@"
api-version: "1.18"
depend:
  - "PvPControl"
