name: "PVPControl_API_Consumer"
main: "com.gmail.nowyarek.pvpcontrol.components.api.consumer.PvPControl_API_Consumer"
version: "@PLUGIN_VERSION@"
author: "IdkMan2"
api-version: "1.18"
depend:
  - "PvPControl"
